name: rubisUHC
version: 1.0
author: GameBlack
main: fr.gameblack.rubisuhc.Main
api-version: 1.12.2
commands:
  rcmsg:
    description: Commande de debug
  giverole:
    description: Commande de debug
  rcnerf:
    description: Commande rôle GameBlack
  rcbonus:
    description: Commande rôle Toinou
  giveorbe:
    description: Give orbe
  rcorbe:
    description: orbe
  rcrecrut:
    description: Commande rôle GameBlack
  rcinspect:
    description: Commande rôle GameBlack
  rcpoints:
    description: Commande rôle Ange
  rcsang:
    description: Commande rôle Sang
  rcnuit:
    description: Commande rôle Ténèbre
  rcsacrifice:
    description: Commande rôle Electrique et Expérimental
  rcblind:
    description: Commande rôle Ténèbre
  start:
    description: Permet de lancer la partie
  rccube:
    description: Commande rôle Joko
  rcban:
    description: Commande rôle Kzou
  resetinv:
    description: admin
  addrole:
    description: Ajouter un role à la compo
  removerole:
    description: Supprimer un role à la compo
  compo:
    description: Voir la compo
  rceffet:
    description: Voir ses poucentage d'effet
  rcsteal:
    description: Commande rôle Joko, Trial et Tronconeuse
  rcspeed:
    description: Commande rôle Farmeurimmo
  rcabso:
    description: Commande rôle Farmeurimmo
  rcdisperse:
    description: Commande rôle Kzou
  rcop:
    description: Commande rôle Kzou
  skipepisode:
    description: Permet de passer un épisode
  rcdon:
    description: Commande rôle Maka
  create:
    description: Créer une partie